apiVersion: v1
kind: Pod
metadata:
  name: "webapp"
  namespace: default
  labels:
    app: "webapp"
spec:
  containers:
  - name: webapp
    image: "richardchesterwood/k8s-fleetman-webapp-angular:release0"
    resources:
      limits:
        cpu: 200m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 200Mi
  restartPolicy: Always